export const config = {
    appName: "react-redux-boilerplate",
    sitename: "myRedux",
    hostname: "test.com",
    default_timezone:100,
    env: "development",
    allowedExtensions: {
        image: [
            "image/jpeg",
            "image/jpe",
            "image/jpg",
            "image/png",
            "image/gif"
        ],
        document: [
            "application/pdf",
            "application/vnd.ms-excel",
            "application/vnd.ms-excel.addin.macroenabled.12",
            "application/vnd.ms-excel.sheet.binary.macroenabled.12",
            "application/vnd.ms-excel.sheet.macroenabled.12",
            "application/vnd.ms-excel.template.macroenabled.12",
            "application/vnd.ms-word.document.macroenabled.12",
            "application/vnd.ms-works",
            "application/vnd.ms-powerpoint",
            "application/vnd.ms-powerpoint.addin.macroenabled.12",
            "application/vnd.ms-powerpoint.presentation.macroenabled.12",
            "application/vnd.ms-powerpoint.slideshow.macroenabled.12",
            "application/vnd.ms-powerpoint.template.macroenabled.12",
            "application/vnd.openofficeorg.extension",
            "application/vnd.openxmlformats-officedocument.presentationml.presentation",
            "application/vnd.openxmlformats-officedocument.presentationml.slide",
            "application/vnd.openxmlformats-officedocument.presentationml.slideshow",
            "application/vnd.openxmlformats-officedocument.presentationml.template",
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            "application/vnd.openxmlformats-officedocument.spreadsheetml.template",
            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            "application/vnd.openxmlformats-officedocument.wordprocessingml.template",
        ],
        audio: ["audio/mp3", "audio/mpeg", "audio/ogg"],
        video: ["video/mp4", "video/mpeg", "video/ogg"],
    },
};
